# Generated by Django 2.0.2 on 2018-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('salt', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=30)),
                ('gender', models.NullBooleanField()),
                ('hobby', models.CharField(default='', max_length=200, null=True)),
                ('birth', models.DateField(default=None, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pic', models.ImageField(default='user_pic/head.png', upload_to='user_pic')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
