# Generated by Django 2.0.2 on 2018-11-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('actor', models.CharField(max_length=120, null=True)),
                ('image', models.CharField(max_length=150, null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('time', models.CharField(max_length=80, null=True)),
                ('index', models.IntegerField()),
            ],
            options={
                'db_table': 't_films',
            },
        ),
    ]
