# Generated by Django 2.0.2 on 2018-10-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, unique=True)),
                ('gprice', models.FloatField(db_column='price')),
                ('fk_cg', models.ForeignKey(db_column='cate_id', on_delete=django.db.models.deletion.CASCADE, to='testapp.Category')),
            ],
            options={
                'db_table': 't_goods',
            },
        ),
    ]
