# Generated by Django 2.0.2 on 2018-10-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=30)),
                ('expire', models.SmallIntegerField()),
            ],
            options={
                'db_table': 't_course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.NullBooleanField()),
                ('sid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_student',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='testapp.Student'),
        ),
    ]
