# Generated by Django 2.0.2 on 2018-10-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20181026_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=20)),
                ('expire', models.SmallIntegerField()),
            ],
            options={
                'db_table': 't_passport',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'db_table': 't_person',
            },
        ),
        migrations.AddField(
            model_name='passport',
            name='per',
            field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='testapp.Person'),
        ),
    ]
