# Generated by Django 2.0.2 on 2018-10-31 15:03

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.NullBooleanField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('birth', models.DateField(null=True)),
                ('modify_time', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.fields.Empty, to='dept.Department')),
            ],
            options={
                'db_table': 't_emp',
            },
        ),
    ]
